/**
 * start-dev.cjs
 * Starts backend + opens public tunnels + starts Vite dev server.
 * Writes tunnel URLs into .env BEFORE starting Vite so QR codes
 * encode the correct public URL from the start.
 *
 * Usage (from inside web/ folder):
 *   node start-dev.cjs
 *
 * How it works:
 *   1. Start backend
 *   2. Open two localtunnel tunnels (backend + web)
 *   3. Write public URLs into .env
 *   4. Start Vite AFTER .env is written
 *   5. Open the app via the tunnel URL shown — QR codes will be scannable anywhere
 */

const { spawn } = require("child_process");
const localtunnel = require("localtunnel");
const fs = require("fs");
const path = require("path");

const WEB_PORT = 5173;
const BACKEND_PORT = 5000;
const WEB_ENV = path.join(__dirname, ".env");
const BACKEND_DIR = path.join(__dirname, "..", "backend");

function writeEnv(webUrl, apiUrl) {
    const content = [
        "# Auto-generated by start-dev.cjs - do not edit manually",
        "",
        `VITE_WEB_URL=${webUrl}`,
        `VITE_API_URL=${apiUrl}`,
        "",
    ].join("\n");
    fs.writeFileSync(WEB_ENV, content, "utf8");
}

function spawnProc(cmd, args, cwd, label) {
    const p = spawn(cmd, args, { cwd, shell: true, stdio: "inherit" });
    p.on("error", (e) => console.error(`[${label}] error: ${e.message}`));
    p.on("exit", (c) => console.log(`[${label}] exited with code ${c}`));
    return p;
}

(async () => {
    // ── Step 1: Start backend ──────────────────────────────
    console.log("\n[1/4] Starting backend on port " + BACKEND_PORT + "...");
    spawnProc("node", ["app.js"], BACKEND_DIR, "backend");
    await new Promise((r) => setTimeout(r, 2000));

    // ── Step 2: Open tunnels ───────────────────────────────
    console.log("[2/4] Opening public tunnels...");
    let backendTunnel, webTunnel;
    try {
        [backendTunnel, webTunnel] = await Promise.all([
            localtunnel({ port: BACKEND_PORT }),
            localtunnel({ port: WEB_PORT }),
        ]);
    } catch (err) {
        console.error("[ERROR] Could not open tunnels:", err.message);
        console.log("        Falling back to local IP mode.");
        console.log("        QR codes will only work on the same WiFi network.");
        // Start Vite without tunnel
        spawnProc("npm", ["run", "dev"], __dirname, "web");
        return;
    }

    const apiUrl = backendTunnel.url;
    const webUrl = webTunnel.url;

    // ── Step 3: Write .env BEFORE starting Vite ───────────
    console.log("[3/4] Writing public URLs to .env...");
    writeEnv(webUrl, apiUrl);

    // Update backend CALLBACK_URL
    const backendEnvPath = path.join(BACKEND_DIR, ".env");
    let benv = fs.readFileSync(backendEnvPath, "utf8");
    benv = benv.replace(/^CALLBACK_URL=.*/m, `CALLBACK_URL=${apiUrl}/callback`);
    fs.writeFileSync(backendEnvPath, benv, "utf8");

    backendTunnel.on("close", () => console.log("\n[WARN] Backend tunnel closed. Restart to reconnect."));
    webTunnel.on("close", () => console.log("\n[WARN] Web tunnel closed. Restart to reconnect."));

    // ── Step 4: Start Vite AFTER .env is written ──────────
    console.log("[4/4] Starting Vite dev server...");
    spawnProc("npm", ["run", "dev"], __dirname, "web");

    // ── Print instructions ─────────────────────────────────
    setTimeout(() => {
        console.log("\n" + "=".repeat(60));
        console.log("  SCANPESA IS RUNNING");
        console.log("=".repeat(60));
        console.log("\n  Open this URL in your browser to generate QR codes:");
        console.log(`  --> ${webUrl}\n`);
        console.log("  IMPORTANT: Open the app using the URL above.");
        console.log("  QR codes will encode that public URL automatically.");
        console.log("  Any phone can scan them — no WiFi required.\n");
        console.log(`  Backend API:  ${apiUrl}`);
        console.log(`  Callback URL: ${apiUrl}/callback`);
        console.log("=".repeat(60) + "\n");
    }, 3000);
})();
