/**
 * start-dev.cjs
 * Starts backend + Vite dev server + two localtunnel tunnels.
 * Auto-writes public URLs into web/.env so QR codes are always scannable.
 *
 * Usage:  node start-dev.cjs   (run from inside the web/ folder)
 */

const { spawn } = require("child_process");
const localtunnel = require("localtunnel");
const fs = require("fs");
const path = require("path");

const WEB_PORT = 5173;
const BACKEND_PORT = 5000;
const WEB_ENV = path.join(__dirname, ".env");
const BACKEND_DIR = path.join(__dirname, "..", "backend");

function writeEnv(webUrl, apiUrl) {
    const content = [
        "# Auto-generated by start-dev.cjs - do not edit manually",
        "",
        "# Public tunnel URL for the web app (encoded into QR codes)",
        `VITE_WEB_URL=${webUrl}`,
        "",
        "# Public tunnel URL for the backend (STK Push API)",
        `VITE_API_URL=${apiUrl}`,
        "",
    ].join("\n");

    fs.writeFileSync(WEB_ENV, content, "utf8");
    console.log("\n[OK] .env updated:");
    console.log(`     VITE_WEB_URL = ${webUrl}`);
    console.log(`     VITE_API_URL = ${apiUrl}`);
    console.log(`\n[INFO] QR codes will open: ${webUrl}/pay?...\n`);
}

function spawnProc(cmd, args, cwd, label) {
    const p = spawn(cmd, args, { cwd, shell: true, stdio: "inherit" });
    p.on("error", (e) => console.error(`[${label}] error: ${e.message}`));
    p.on("exit", (c) => console.log(`[${label}] exited with code ${c}`));
    return p;
}

(async () => {
    console.log("[1/4] Starting backend on port " + BACKEND_PORT + "...");
    spawnProc("node", ["app.js"], BACKEND_DIR, "backend");

    await new Promise((r) => setTimeout(r, 2000));

    console.log("[2/4] Opening public tunnels...");

    const [backendTunnel, webTunnel] = await Promise.all([
        localtunnel({ port: BACKEND_PORT }),
        localtunnel({ port: WEB_PORT }),
    ]);

    const apiUrl = backendTunnel.url;
    const webUrl = webTunnel.url;

    writeEnv(webUrl, apiUrl);

    // Update backend CALLBACK_URL
    const backendEnvPath = path.join(BACKEND_DIR, ".env");
    let benv = fs.readFileSync(backendEnvPath, "utf8");
    benv = benv.replace(/^CALLBACK_URL=.*/m, `CALLBACK_URL=${apiUrl}/callback`);
    fs.writeFileSync(backendEnvPath, benv, "utf8");
    console.log(`[OK] CALLBACK_URL = ${apiUrl}/callback`);

    backendTunnel.on("close", () => console.log("[WARN] Backend tunnel closed - restart to reconnect"));
    webTunnel.on("close", () => console.log("[WARN] Web tunnel closed - restart to reconnect"));

    console.log("[3/4] Starting Vite dev server on port " + WEB_PORT + "...");
    spawnProc("npm", ["run", "dev"], __dirname, "web");

    console.log("[4/4] All services running.");
    console.log("      Open your browser, go to the generate page, create a QR,");
    console.log("      then scan it with Google Lens on any phone.\n");
})();
